/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.AluguelDB;
import dao.ClienteDB;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.Aluguel;
import models.Cliente;

/**
 *
 * @author amaury
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        carregaTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlugueis = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNovoCliente = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuClientesInativos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuNovoVeiculo = new javax.swing.JMenuItem();
        menuVeiculos = new javax.swing.JMenuItem();
        menuVeiculosAtivos = new javax.swing.JMenuItem();
        menuVeiculosInativos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuUsuariosAtivos = new javax.swing.JMenuItem();
        menuUsuariosInativos = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menuRealizarAluguel = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alugueis vencidos"));

        tbAlugueis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Aluguel", "Valor", "Devolução", "Nome", "CPF", "Telefone", "Modelo", "Placa", "Ano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAlugueis);
        if (tbAlugueis.getColumnModel().getColumnCount() > 0) {
            tbAlugueis.getColumnModel().getColumn(0).setMinWidth(50);
            tbAlugueis.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Clientes");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        menuNovoCliente.setText("Novo");
        menuNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuNovoCliente);

        menuClientes.setText("Cadastrados");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuClientes);

        menuClientesInativos.setText("Inativos");
        menuClientesInativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesInativosActionPerformed(evt);
            }
        });
        jMenu1.add(menuClientesInativos);

        jMenuBar1.add(jMenu1);

        jMenu8.setText("Veiculos");

        menuNovoVeiculo.setText("Novo");
        menuNovoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoVeiculoActionPerformed(evt);
            }
        });
        jMenu8.add(menuNovoVeiculo);

        menuVeiculos.setText("Disponiveis");
        menuVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVeiculosActionPerformed(evt);
            }
        });
        jMenu8.add(menuVeiculos);

        menuVeiculosAtivos.setText("Ativos");
        menuVeiculosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVeiculosAtivosActionPerformed(evt);
            }
        });
        jMenu8.add(menuVeiculosAtivos);

        menuVeiculosInativos.setText("Inativos");
        menuVeiculosInativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVeiculosInativosActionPerformed(evt);
            }
        });
        jMenu8.add(menuVeiculosInativos);

        jMenuBar1.add(jMenu8);

        jMenu3.setText("Usuários");

        jMenuItem1.setText("Novo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        menuUsuariosAtivos.setText("Ativos");
        menuUsuariosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosAtivosActionPerformed(evt);
            }
        });
        jMenu3.add(menuUsuariosAtivos);

        menuUsuariosInativos.setText("Inativos");
        menuUsuariosInativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosInativosActionPerformed(evt);
            }
        });
        jMenu3.add(menuUsuariosInativos);

        jMenuBar1.add(jMenu3);

        jMenu9.setText("Aluguel");

        menuRealizarAluguel.setText("Realizar aluguel");
        menuRealizarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRealizarAluguelActionPerformed(evt);
            }
        });
        jMenu9.add(menuRealizarAluguel);

        jMenuItem2.setText("Veiculos alugados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem2);

        jMenuItem3.setText("Todos alugueis");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem3);

        jMenuBar1.add(jMenu9);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregaTabela(){
        
        DefaultTableModel modelo = (DefaultTableModel) tbAlugueis.getModel();
        modelo.setNumRows(0);
       
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        
        
        tbAlugueis.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(1).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(3).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(4).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(5).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(6).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(7).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(8).setCellRenderer(centralizado);
        tbAlugueis.getColumnModel().getColumn(9).setCellRenderer(centralizado);
        
        AluguelDB alugueldb = new AluguelDB();
        ArrayList<Aluguel> alugueis = alugueldb.listarAlugueisVencidos();
        
        if (alugueis != null){
            for (Aluguel a : alugueis){
                modelo.addRow(new Object[]{
                
                    a.getIdAluguel(),
                    a.getDtAluguel(),
                    a.getValor(),
                    a.getDtDevolucao(),
                    a.getNome(),
                    a.getCPF(),
                    a.getTelefone(),
                    a.getModelo(),
                    a.getPlaca(),
                    a.getAno()
//                    a.getIsActive()
                
                });
            }
        }

    }
    
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        UsuariosNovo newUser = new UsuariosNovo();
        newUser.setLocationRelativeTo(null);
        newUser.setVisible(true);
        newUser.setTitle("Novo usuario");
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2MousePressed

    private void menuUsuariosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosAtivosActionPerformed
        // TODO add your handling code here:
        UsuariosAtivos lu = new UsuariosAtivos();
        lu.setLocationRelativeTo(null);
        lu.setVisible(true);
        lu.setTitle("Usuarios ativos");
        this.dispose();
    }//GEN-LAST:event_menuUsuariosAtivosActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        // TODO add your handling code here:
        ClientesAtivos ct = new ClientesAtivos();
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
        ct.setTitle("Clientes ativos");
        this.dispose();
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuClientesInativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesInativosActionPerformed
        // TODO add your handling code here:
        ClientesInativos clt = new ClientesInativos();
        clt.setLocationRelativeTo(null);
        clt.setVisible(true);
        clt.setTitle("Clientes inativos");
        this.dispose();
    }//GEN-LAST:event_menuClientesInativosActionPerformed

    private void menuVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVeiculosActionPerformed
        // TODO add your handling code here:
        VeiculosDisponiveis v = new VeiculosDisponiveis();
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuVeiculosActionPerformed

    private void menuVeiculosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVeiculosAtivosActionPerformed
        // TODO add your handling code here:
        VeiculosAtivos v = new VeiculosAtivos();
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        v.setTitle("Veiculos Ativos");
        this.dispose();
    }//GEN-LAST:event_menuVeiculosAtivosActionPerformed

    private void menuVeiculosInativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVeiculosInativosActionPerformed
        // TODO add your handling code here:
        VeiculosInativos v = new VeiculosInativos();
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        v.setTitle("Veiculos Inativos");
        this.dispose();
    }//GEN-LAST:event_menuVeiculosInativosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AluguelReceber a = new AluguelReceber();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuRealizarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRealizarAluguelActionPerformed
        // TODO add your handling code here:
        AluguelRealizar a = new AluguelRealizar();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setTitle("Realizar novo aluguel");
        this.dispose();
    }//GEN-LAST:event_menuRealizarAluguelActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        ClientesInativos c = new ClientesInativos();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        c.setTitle("Clientes inativos");
        this.dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void menuNovoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoVeiculoActionPerformed
        // TODO add your handling code here:
        
        VeiculosNovo v = new VeiculosNovo();
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNovoVeiculoActionPerformed

    private void menuNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoClienteActionPerformed
        // TODO add your handling code here:
        ClientesNovo c = new ClientesNovo();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        c.setTitle("Novo Cliente");
        this.dispose();
    }//GEN-LAST:event_menuNovoClienteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        AluguelListarTodos a = new AluguelListarTodos();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setTitle("Litagem de todos os alugueis");
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuUsuariosInativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosInativosActionPerformed
        // TODO add your handling code here:
        UsuariosInativos u = new UsuariosInativos();
        u.setLocationRelativeTo(null);
        u.setVisible(true);
        u.setTitle("Usuarios inativos");
        this.dispose();
    }//GEN-LAST:event_menuUsuariosInativosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuClientesInativos;
    private javax.swing.JMenuItem menuNovoCliente;
    private javax.swing.JMenuItem menuNovoVeiculo;
    private javax.swing.JMenuItem menuRealizarAluguel;
    private javax.swing.JMenuItem menuUsuariosAtivos;
    private javax.swing.JMenuItem menuUsuariosInativos;
    private javax.swing.JMenuItem menuVeiculos;
    private javax.swing.JMenuItem menuVeiculosAtivos;
    private javax.swing.JMenuItem menuVeiculosInativos;
    private javax.swing.JTable tbAlugueis;
    // End of variables declaration//GEN-END:variables
}
